import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
// リファクタ用コメント
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
